import localFont from "next/font/local";
import { Josefin_Sans } from 'next/font/google';
import "./globals.css";

const josefinSans = Josefin_Sans({
  subsets: ['latin'], 
  variable: '--font-josefin-sans',
  weight: ['400', '700'], 
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Frontend Mentor - Todo-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className={`${josefinSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
