import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin-sans",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Frontend Mentor | Todo app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className={`${josefinSans.variable} min-h-screen bg-LTVeryLightGrayishBlue dark:bg-DTDarkGrayBlue text-LTDarkGrayishBlue dark:text-DTLightGrayishBlue antialiased`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
